

export const POST_AUTH_REQUEST="POST_AUTH_REQUEST";
export const POST_AUTH_FAILURE="POST_AUTH_FAILURE";
export const POST_AUTH_SUCCESS="POST_AUTH_SUCCESS";

export const POST_SIGNUP_SUCCESS="POST_SIGNUP_SUCCESS";